seed: 2024
save_iter: 1
max_save_num: 3

dataset:
  train:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/box/'
    filelist: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/namelist.txt'
    trainsize: 384
    istraining: true
    batch_size: 32
    num_workers: 12
    shuffle: true
  val:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/box/'
    filelist: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/namelist.txt'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 12
    shuffle: false
  test:
    type: 'COSwithBox'
    image_root: ['/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/mask/']
    trainsize: 384
    istraining: false
    batch_size: 32
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%_vflip/']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/ANet/COD/20%/model_best.pth'
    save_indices: [4, 8]
    save_index_names: ['mask', 'edge']
    pose_process: ['tensor_pose_processing_mask', 'tensor_pose_processing_edge']


optimizer:
  type: 'Adam'
  params:
    lr: 0.0001

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.0000001
    warmup_epochs: 0
    total_epochs: 100

model:
  name: 'PANetDS'
  params:
    channels: 64

training:
  epochs: 100
  load: null
  pretrain: null
  gpu_id: '0,1,2,3'
  q_epoch: 20
  best_mae: 1.0
  best_epoch: 1
  val_step: 10
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/ANet/DS/'
  find_unused_parameters: true
  main_output_index: 0
  losses:
      loss1:
        type: ['NCLoss']
        gt_input: ["gt"]
        coef: [1]