seed: 2024
save_iter: 10
max_save_num: 3

dataset:
  train:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/LabelNoiseTrainList/top_10_percent_similarities.txt'
    trainsize: 384
    istraining: true
    batch_size: 16
    num_workers: 12
    shuffle: true
  val:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/LabelNoiseTrainList/namelist_generate_90.0%.txt'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 12
    shuffle: false
  test:
    type: 'COSwithBox'
    image_root: ['/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/mask/']
    trainsize: 384
    istraining: false
    batch_size: 32
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%_vflip/']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/ANet/COD/20%/model_best.pth'
    save_indices: [4, 8]
    save_index_names: ['mask', 'edge']
    pose_process: ['tensor_pose_processing_mask', 'tensor_pose_processing_edge']


optimizer:
  type: 'Adam'
  params:
    lr: 0.0001

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0005
    min_lr: 0.0000005
    warmup_epochs: 5
    total_epochs: 200

model:
  name: 'PANet'
  params:
    channels: 64

training:
  epochs: 200
  load: null
  pretrain: null
  gpu_id: '0,1,2,3'
  best_mae: 1.0
  best_epoch: 1
  val_step: 20
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/ANet/10%/'
  find_unused_parameters: false
  main_output_index: 4
  losses:
      loss1:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.0625]
      loss2:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.125]
      loss3:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.25]
      loss4:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.5]
      loss5:
        type: ['StructureLoss', 'UALoss']
        gt_input: ["gt", "gt"]
        coef: [1, 2]
      loss6:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0]
      loss7:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.125]
      loss8:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.25]
      loss9:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.5]