seed: 2024
save_iter: 5
max_save_num: 3

dataset:
  train1:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/Polyp/TrainDataset/image/'
    gt_root: '/mnt/jixie16t/dataset/Polyp/TrainDataset/mask/'
    file_list: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/configs/Polyp/coreset/coreset1.txt'
    trainsize: 384
    istraining: true
    batch_size: 12
    num_workers: 4
    shuffle: true
  val:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/Polyp/TrainDataset/image/'
    gt_root: '/mnt/jixie16t/dataset/Polyp/TrainDataset/mask/'
    file_list: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/configs/Polyp/coreset/remaining99.txt'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 4
    shuffle: false
    metric: ['MAE', 'IoU']
    pose_process: ['tensor_pose_processing_mask']
  test:
    type: 'COSwithBox'
    image_root: ['/mnt/jixie16t/dataset/Polyp/TrainDataset/image/']
    gt_root: ['/mnt/jixie16t/dataset/Polyp/TrainDataset/mask/']
    file_list: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/configs/Polyp/coreset/remaining99.txt']
    trainsize: 384
    istraining: false
    batch_size: 32
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/Polyp/ANet/coreset/remaining99/']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/Polyp/ANet/1%/epoch_100.pth'
    save_indices: [4, 8]
    save_index_names: ['mask', 'edge']
    pose_process: ['tensor_pose_processing_mask', 'tensor_pose_processing_edge']


optimizer:
  type: 'AdamW'
  params:
    lr: 0.0001

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.0000001
    warmup_epochs: 5
    total_epochs: 100

model:
  name: 'ANet'
  params:
    channels: 64

training:
  epochs: 100
  load: null
  pretrain: null
  gpu_id: '1'
  best_mae: 1.0
  best_epoch: 1
  val_step: 50
  is_validation: false
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12361'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/Polyp/ANet/1%/'
  find_unused_parameters: false
  main_output_index: 4
  losses:
      loss1:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.0625]
      loss2:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.125]
      loss3:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.25]
      loss4:
        type: ['StructureLoss']
        gt_input: ["gt"]
        coef: [0.5]
      loss5:
        type: ['StructureLoss', 'UALoss']
        gt_input: ["gt", "gt"]
        coef: [1, 2]
      loss6:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0]
      loss7:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.125]
      loss8:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.25]
      loss9:
        type: ['DiceLoss']
        gt_input: ["edge"]
        coef: [0.5]