seed: 2024
save_iter: 5
max_save_num: 3

dataset:
  train1:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/middle_remaining_80_percent%/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/LabelNoiseTrainList/remaining_middle_80_percent.txt'
    trainsize: 384
    istraining: true
    batch_size: 24
    num_workers: 6
    shuffle: true
  train2:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/LabelNoiseTrainList/middle_20_percent.txt'
    trainsize: 384
    istraining: true
    batch_size: 6
    num_workers: 6
    shuffle: true
  val:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/COD10K/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/COD10K/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/COD10K/namelist.txt'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 6
    shuffle: false
    pose_process: ['tensor_pose_processing_mask']
    metric: ['MAE', 'IoU']
  test:
    type: 'COSwithNoBox'
    image_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/image/', '/mnt/jixie16t/dataset/COD/CAMO/image/', '/mnt/jixie16t/dataset/COD/COD10K/image/', '/mnt/jixie16t/dataset/COD/NC4K/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/mask/', '/mnt/jixie16t/dataset/COD/CAMO/mask/', '/mnt/jixie16t/dataset/COD/COD10K/mask/', '/mnt/jixie16t/dataset/COD/NC4K/mask/']
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_NCLoss/CHAMELEON_TestingDataset', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_NCLoss/CAMO', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_NCLoss/COD10K', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_NCLoss/NC4K']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PNet/20%_with_ssloss_middle/model_best.pth'
    save_indices: [4]
    save_index_names: ['']
    pose_process: ['tensor_pose_processing_mask']

optimizer:
  type: 'Adam'
  params:
    lr: 0.0004

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.0000001
    warmup_epochs: 5
    total_epochs: 100

model:
  name: 'PNet'
  params:
    backbone: 'pvt'
    channels: 64

training:
  epochs: 100
  load: "/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/PNet/20%_with_nlssloss_middle/epoch_60.pth"
  q_epoch: 60
  pretrain: null
  gpu_id: '2'
  best_mae: 1.0
  best_epoch: 1
  val_step: 1
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12351'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/PNet/20%_with_nlssloss_middle/'
  find_unused_parameters: true
  main_output_index: 4
  losses:
    loss1:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.0625]
    loss2:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.125]
    loss3:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.25]
    loss4:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.5]
    loss5:
      type: ['NLSSLoss', 'UALoss']
      gt_input: ["gt", "gt"]
      coef: [1, 2]
    loss6:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0]
    loss7:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.125]
    loss8:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.25]
    loss9:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.5]
