seed: 2024
save_iter: 5
max_save_num: 3

dataset:
  train1:
    type: 'COSwithNoBoxML'
    image_root: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%/image/'
    gt_root: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%/mask/'
    gt_root2: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%_hflip/mask/'
    gt_root3: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/pseudo_label_80%_vflip/mask/'
    trainsize: 384
    istraining: true
    batch_size: 24
    num_workers: 6
    shuffle: true
  train2:
    type: 'COSwithNoBoxML'
    image_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_train_20%/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_train_20%/mask/'
    gt_root2: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_train_20%/mask/'
    gt_root3: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_train_20%/mask/'
    trainsize: 384
    istraining: true
    batch_size: 6
    num_workers: 6
    shuffle: true
  val:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO/mask/'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 6
    shuffle: false
  test:
    type: 'COSwithNoBox'
    image_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/image/', '/mnt/jixie16t/dataset/COD/CAMO/image/', '/mnt/jixie16t/dataset/COD/COD10K/image/', '/mnt/jixie16t/dataset/COD/NC4K/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/mask/', '/mnt/jixie16t/dataset/COD/CAMO/mask/', '/mnt/jixie16t/dataset/COD/COD10K/mask/', '/mnt/jixie16t/dataset/COD/NC4K/mask/']
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_ncloss/CHAMELEON_TestingDataset', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_ncloss/CAMO', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_ncloss/COD10K', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/PNets/PNet_20_ncloss/NC4K']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PNet/20%_with_ncloss_ml/model_best.pth'
    save_indices: [4]
    save_index_names: ['']
    pose_process: ['tensor_pose_processing_mask']

optimizer:
  type: 'Adam'
  params:
    lr: 0.0004

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.0000001
    warmup_epochs: 5
    total_epochs: 100

model:
  name: 'PNet'
  params:
    backbone: 'res2net'
    channels: 96

training:
  epochs: 100
  load: null
  q_epoch: 60
  pretrain: null
  gpu_id: '0,1,2,3'
  best_mae: 1.0
  best_epoch: 1
  val_step: 1
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PNet/20%_with_ncloss_ml/'
  find_unused_parameters: false
  main_output_index: 4
  losses:
    loss1:
      type: ['NCLoss']
      gt_input: ["gt"]
      coef: [0.0625]
    loss2:
      type: ['NCLoss']
      gt_input: ["gt"]
      coef: [0.125]
    loss3:
      type: ['NCLoss']
      gt_input: ["gt"]
      coef: [0.25]
    loss4:
      type: ['NCLoss']
      gt_input: ["gt"]
      coef: [0.5]
    loss5:
      type: ['NCLoss', 'UALoss', 'NCLoss', 'NCLoss']
      gt_input: ["gt", "gt", "gt2", "gt3"]
      coef: [0.3, 2, 0.3, 0.3]
    loss6:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0]
    loss7:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.125]
    loss8:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.25]
    loss9:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.5]
