seed: 2024
save_iter: 5
max_save_num: 3

dataset:
  train1:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/mask/'
    trainsize: 384
    istraining: true
  val:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/mask/'
    trainsize: 384
    istraining: false

dataloader:
  batch_size: 32
  num_workers: 6
  batch_size_val: 64
  shuffle: true

optimizer:
  type: 'AdamW'
  params:
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0.01
    amsgrad: False

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0004
    min_lr: 0.0000004
    warmup_epochs: 10
    total_epochs: 100

model:
  name: 'UNetResNet50'

training:
  epochs: 100
  load: null
  q_epoch: 60
  pretrain: null
  gpu_id: '0'
  best_mae: 1.0
  best_epoch: 1
  val_step: 1
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/UNet/fully_train/'
  grad_accum: 1
  main_output_index: 0
  losses:
    loss1:
      type: ['StructureLoss', 'UALoss']
      gt_input: ["gt"]
      coef: [1, 2]
