seed: 2024
save_iter: 5
max_save_num: 3

dataset:
  train1:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/COD/ANet/coreset/remaining99/mask/'
    file_list: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/configs/COD/coreset/remaining99.txt'
    trainsize: 384
    istraining: true
    batch_size: 24
    num_workers: 0
    shuffle: true
  train2:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/mask/'
    file_list: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/configs/COD/coreset/coreset1.txt'
    repeat: 20
    trainsize: 384
    istraining: true
    batch_size: 6
    num_workers: 2
    shuffle: true
  val:
    type: 'COSwithNoBox'
    image_root: '/mnt/jixie16t/dataset/COD/COD10K/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/COD10K/mask/'
    file_list: '/mnt/jixie16t/dataset/COD/COD10K/namelist.txt'
    trainsize: 384
    istraining: false
    batch_size: 64
    num_workers: 4
    shuffle: false
    pose_process: ['tensor_pose_processing_mask']
    metric: ['MAE', 'IoU']
  test:
    type: 'COSwithNoBox'
    image_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/image/', '/mnt/jixie16t/dataset/COD/CAMO/image/', '/mnt/jixie16t/dataset/COD/COD10K/image/', '/mnt/jixie16t/dataset/COD/NC4K/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/mask/', '/mnt/jixie16t/dataset/COD/CAMO/mask/', '/mnt/jixie16t/dataset/COD/COD10K/mask/', '/mnt/jixie16t/dataset/COD/NC4K/mask/']
    file_list: ['/mnt/jixie16t/dataset/COD/CHAMELEON_TestingDataset/namelist.txt', '/mnt/jixie16t/dataset/COD/CAMO/namelist.txt', '/mnt/jixie16t/dataset/COD/COD10K/namelist.txt', '/mnt/jixie16t/dataset/COD/NC4K/namelist.txt']
    trainsize: 384
    istraining: false
    batch_size: 12
    num_workers: 2
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/COD/PNet/1%/CHAMELEON_TestingDataset', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/COD/PNet/1%/CAMO', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/COD/PNet/1%/COD10K', '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/results/COD/PNet/1%/NC4K']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/PNet/1%/epoch_100.pth'
    save_indices: [4]
    save_index_names: ['']
    pose_process: ['tensor_pose_processing_mask']

optimizer:
  type: 'AdamW'
  params:
    lr: 0.0004

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.0000001
    warmup_epochs: 0
    total_epochs: 100

model:
  name: 'PNet'
  params:
    channels: 64

training:
  epochs: 100
  load: null
  q_epoch: 20
  pretrain: null
  gpu_id: '0'
  best_mae: 1.0
  best_epoch: 1
  val_step: 10
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '1235'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/PNet/1%/'
  find_unused_parameters: true
  main_output_index: 4
  losses:
    loss1:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.0625]
    loss2:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.125]
    loss3:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.25]
    loss4:
      type: ['NLSSLoss']
      gt_input: ["gt"]
      coef: [0.5]
    loss5:
      type: ['NLSSLoss', 'UALoss']
      gt_input: ["gt", "gt"]
      coef: [1, 2]
    loss6:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0]
    loss7:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.125]
    loss8:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.25]
    loss9:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.5]
