seed: 2024
save_iter: 10
max_save_num: 3

dataset:
  train:
    type: 'ImageInpainting'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/box/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/namelist.txt'
    trainsize: 256
    istraining: true
    batch_size: 64
    num_workers: 8
    shuffle: true
    repeat: 20
  val:
    type: 'ImageInpainting'
    image_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/box/'
    file_list: '/mnt/jixie16t/dataset/COD/CAMO_COD_train/namelist.txt'
    trainsize: 256
    istraining: false
    batch_size: 64
    num_workers: 8
    shuffle: false
  test:
    type: 'ImageInpainting'
    image_root: ['/mnt/jixie16t/dataset/COD/CAMO_COD_train/image/']
    gt_root: ['/mnt/jixie16t/dataset/COD/CAMO_COD_train/box/']
    trainsize: 256
    istraining: false
    batch_size: 32
    num_workers: 6
    shuffle: false
    save_path: ['/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/data/ANet/ImageInpainting/']
    load: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/ANet/DS/epoch_100.pth'
    save_indices: [0]
    save_index_names: ['mask']
    pose_process: ['tensor_pose_processing_inpainting']


optimizer:
  type: 'Adam'
  params:
    lr: 0.0001

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.0001
    min_lr: 0.000001
    warmup_epochs: 0
    total_epochs: 300

model:
  name: 'UNet'
  params:
    in_channels: 3

training:
  epochs: 100
  load: null
  pretrain: null
  gpu_id: '0,1,2,3'
  q_epoch: 20
  best_mae: 1.0
  best_epoch: 1
  val_step: 1000
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/COD/ANet/DS_Out/'
  find_unused_parameters: false
  main_output_index: 0
  losses:
      loss1:
        type: ['L1Loss', 'GradientLoss']
        gt_input: ["gt", 'gt']
        coef: [1, 1]