seed: 2024

dataset:
  train:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/zj/zj/works_in_phd/ECCV2024/github_release/NoisyCOD/data/LabelNoiseTrainDataset/CAMO_COD_train_1%/image/'
    gt_root: '/mnt/jixie16t/zj/zj/works_in_phd/ECCV2024/github_release/NoisyCOD/data/LabelNoiseTrainDataset/CAMO_COD_train_1%/mask/'
    trainsize: 384
    istraining: true
  val:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/zj/zj/works_in_phd/ECCV2024/github_release/NoisyCOD/data/LabelNoiseTrainDataset/CAMO_COD_generate_99%/image/'
    gt_root: '/mnt/jixie16t/zj/zj/works_in_phd/ECCV2024/github_release/NoisyCOD/data/LabelNoiseTrainDataset/CAMO_COD_generate_99%/mask/'
    trainsize: 384
    istraining: false

dataloader:
  batch_size: 16
  num_workers: 6
  shuffle: true

optimizer:
  type: 'Adam'
  params:
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0

scheduler:
  type: 'CosineAnnealingLR'
  params:
    T_max: 200  # 余弦退火周期的长度
    eta_min: 0.000001  # 最小学习率

model:
  name: 'Network'

training:
  epochs: 200
  q_epoch: 20
  load: null
  gpu_id: '0'
  best_mae: 1.0
  best_epoch: 1
  val_step: 10
  save_path: './weight/ANet/1%/'
