seed: 2024
save_iter: 1
max_save_num: 3

dataset:
  train:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/LVIS/image/'
    gt_root: '/mnt/jixie16t/dataset/LVIS/mask_coconut/'
    trainsize: 224
    istraining: true
    batch_size: 128
    num_workers: 8
    shuffle: true
  val:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/mask/'
    trainsize: 224
    istraining: false
    batch_size: 64
    num_workers: 6
    shuffle: false

optimizer:
  type: 'Adam'
  params:
    lr: 0.00048

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.00048
    min_lr: 0.00000048
    warmup_epochs: 0
    total_epochs: 200

model:
  name: 'UNet'

training:
  epochs: 200
  q_epoch: 20
  load: null
  pretrain: null
  gpu_id: '0,1,2,3'
  best_mae: 1.0
  best_epoch: 1
  val_step: 5
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PANet/LVISUNet/'
  find_unused_parameters: false
  main_output_index: 0
  losses:
    loss1:
      type: ['StructureLoss', 'UALoss']
      gt_input: ["gt", 'gt']
      coef: [1, 2]