seed: 2024
save_iter: 1
max_save_num: 5

dataset:
  train:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/LVIS/image/'
    gt_root: '/mnt/jixie16t/dataset/LVIS/mask_coconut/'
    trainsize: 288
    istraining: true
  val:
    type: 'COSwithBox'
    image_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/image/'
    gt_root: '/mnt/jixie16t/dataset/COD/LabelNoiseTrainDataset/CAMO_COD_generate_80%/mask/'
    trainsize: 288
    istraining: false

dataloader:
  batch_size: 64
  num_workers: 8
  batch_size_val: 64
  shuffle: true

optimizer:
  type: 'AdamW'
  params:
    lr: 0.0004
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0.01
    amsgrad: False

scheduler:
  type: 'LinearCosineAnnealingLR'
  params:
    max_lr: 0.00048
    min_lr: 0.00000048
    warmup_epochs: 0
    total_epochs: 200

model:
  name: 'PANet'

training:
  epochs: 200
  q_epoch: 20
  load: /mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PANet/LVIS/epoch_116.pth
  pretrain: null
  gpu_id: '0,1,2,3'
  best_mae: 1.0
  best_epoch: 1
  val_step: 10
  MASTER_ADDR: 'localhost'
  MASTER_PORT: '12355'
  save_path: '/mnt/jixie16t/zj/zj/works_in_phd/NoisyCOS/weight/PANet/LVIS/'
  grad_accum: 1
  losses:
    loss1:
      type: ['StructureLoss']
      gt_input: ["gt"]
      coef: [0.0625]
    loss2:
      type: ['StructureLoss']
      gt_input: ["gt"]
      coef: [0.125]
    loss3:
      type: ['StructureLoss']
      gt_input: ["gt"]
      coef: [0.25]
    loss4:
      type: ['StructureLoss']
      gt_input: ["gt"]
      coef: [0.5]
    loss5:
      type: ['StructureLoss', 'UALoss']
      gt_input: ["gt"]
      coef: [1, 2]
    loss6:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0]
    loss7:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [0.5]
    loss8:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [1]
    loss9:
      type: ['DiceLoss']
      gt_input: ["edge"]
      coef: [2]
